environment: "dev"
serviceAccountName: accelerator-sa
createIngress: false

net:
  host: "api-dev.accelerator.dsgov.demo.nuvalence.io"

env:
  ALLOWED_ORIGINS: "http://localhost:4200, http://localhost:4201, https://api-dev.accelerator.dsgov.demo.nuvalence.io, https://agency-dev.accelerator.dsgov.demo.nuvalence.io, https://public-dev.accelerator.dsgov.demo.nuvalence.io, https://employer-dev.accelerator.dsgov.demo.nuvalence.io"
  CERBOS_URI: "127.0.0.1:3592"
  DB_CONNECTION_URL: "jdbc:postgresql://127.0.0.1:5432/accelerator-dev-user-management-db"
  DB_USERNAME: "${sm://projects/accelerator-dev-b6f2/secrets/accelerator-dev-db-user/versions/latest}"
  DB_PASSWORD: "${sm://projects/accelerator-dev-b6f2/secrets/accelerator-dev-db-pass/versions/latest}"
  GCP_PROJECT_ID: "accelerator-dev-b6f2"
  SELF_SIGN_PUBLIC_KEY: "${sm://projects/accelerator-dev-b6f2/secrets/accelerator-self-signed-token-public-key/versions/latest}"
  SELF_SIGN_PRIVATE_KEY: "${sm://projects/accelerator-dev-b6f2/secrets/accelerator-self-signed-token-private-key/versions/latest}"
  TOKEN_PRIVATE_KEY_SECRET: "accelerator-self-signed-token-private-key"
  TOKEN_ISSUER: "accelerator"
  TOKEN_PRIVATE_KEY_VERSION: "latest"
  OTEL_SAMPLER_PROBABILITY: 1.0 # valid values: [0.0, 1.0]
